// Run with PLAYWRIGHT_MODULE set when Playwright is provided by the environment.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
 const errors=[];
 const context=await browser.newContext({viewport:{width:1280,height:900}});
 await context.addInitScript(()=>{window.registeredTools={};Object.defineProperty(document,'modelContext',{value:{registerTool(t){window.registeredTools[t.name]=t;}}});});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.TEST_URL||'http://127.0.0.1:5173');
 await page.getByRole('button',{name:'进入草地'}).waitFor();
 await page.screenshot({path:'/tmp/moss-desktop.png'});
 const state=()=>page.evaluate(()=>window.registeredTools.get_run_status.execute({}));
 await page.getByRole('button',{name:'进入草地'}).click();
 await page.keyboard.down('d');await page.waitForTimeout(700);await page.keyboard.up('d');
 assert.ok((await state()).position.x>30,'keyboard moves character');
 await page.getByRole('button',{name:'暂停 Ⅱ'}).click();const paused=await state();
 await page.waitForTimeout(300);assert.deepEqual(await state(),paused,'pause freezes simulation');
 await page.getByRole('button',{name:'继续冒险'}).click();
 await page.waitForFunction(()=>Number(document.getElementById('kills').textContent)>0,{},{timeout:20000});
 await page.screenshot({path:'/tmp/moss-playing.png'});
 const names=await page.evaluate(()=>Object.keys(window.registeredTools));assert.equal(names.length,3);
 const invalid=await page.evaluate(()=>{try{window.registeredTools.choose_upgrade.execute({id:'invalid'});return false;}catch{return true;}});assert.ok(invalid);
 if((await state()).status==='playing')await page.evaluate(()=>window.registeredTools.pause_run.execute({}));
 assert.equal((await state()).status,'paused');
 await page.getByRole('button',{name:'重新开始本局'}).click();assert.equal((await state()).level,1);assert.equal((await state()).kills,0);
 await context.close();
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2});
 await mobile.addInitScript(()=>{window.registeredTools={};Object.defineProperty(document,'modelContext',{value:{registerTool(t){window.registeredTools[t.name]=t;}}});});
 const p=await mobile.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.TEST_URL||'http://127.0.0.1:5173');
 await p.getByRole('button',{name:'进入草地'}).waitFor();await p.screenshot({path:'/tmp/moss-mobile.png'});
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'no horizontal overflow');
 await p.getByRole('button',{name:'进入草地'}).tap();
 const box=await p.locator('#joystick').boundingBox();
 const cdp=await mobile.newCDPSession(p);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+box.width/2+30,y:box.y+box.height/2}]});
 await p.waitForTimeout(650);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 const moved=await p.evaluate(()=>window.registeredTools.get_run_status.execute({}));assert.ok(moved.position.x>25,'touch moves character');
 await p.waitForTimeout(250);const stopped=await p.evaluate(()=>window.registeredTools.get_run_status.execute({}));assert.equal(stopped.position.x,moved.position.x,'touch release stops character');
 await p.setViewportSize({width:844,height:390});await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[],'no browser errors');
 console.log('PASS: desktop start, movement, automatic kill, pause/resume/restart; mobile joystick/release/rotation; WebMCP read/pause/error path.');
 await browser.close();
})().catch(e=>{console.error(e);process.exitCode=1;});
